apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-dotnet
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-dotnet
spec:
  params:
    - name: run-image
      value: your-registry.io/project/tanzu-dotnet
  source:
    git:
      url: https://github.com
      ref:
        branch: main
